### ISSUE TITLE
moment is not defined

### ISSUE THREAD

**Issue by am88tech** [amittkSharma/extended-datetimepicker#2]
While trying to use your plugin, I am getting an error saying moment is not defined. Any suggestions please?

**Comment by amittkSharma** [comment]
Hi Abhishek, 

Please check whether your node_modules or bower_modules contains moment folder depending of the method of installation. If not please try to re-install "moment". Or please check the version of moment in pre-installed in project and version being used in the datetimepicker.

Thanks and regards
Amit
